### ISSUE TITLE
Your....

### ISSUE THREAD

**Issue by NiAsterisk** [thank-you-github/thank-you-github#113]
Your fandom is [problematic](https://wubthecaptain.eu/articles/why-i-dont-support-github.html) and toxic to free software.

**Comment by thank-you-github** [comment]
Note taken, thanks!

**Comment by zQueal** [comment]
This is probably just white noise -- but I'm going to throw down anyways.

Berating those who are thankful to a company who has built an ecosystem which fosters FOSS development on a never before seen scale is pretty goddamn pointless. No matter how much you love or hate Github it was here when we needed it the most. 7 years ago when Github was first released I joined and stepped into the world of FOSS development. Since then, I've been able to pay for my education, get a wonderful career where I explore my passion every single day, and purchase a home because of what I learned on a single platform; Github. Github _is_ a company. A company will always look out for its own interests for self preservation; none are the exception, either. Not the Linux Foundation, EFF, or even the FSF.

So say what you want but being thankful in the middle of a shitstorm of bullshit by spoiled brats who probably never had to live without these fucking _amazing_ collaborative tools is pretty moot. Especially since you use the platform you're criticizing to voice your opinion.

Or at least that's my two cents.
